### ISSUE TITLE
user table with database

### ISSUE THREAD

**Issue by Davessonn** [ivangfr/springboot-react-basic-auth#8]
Sorry for writing here, but unfortunately I can't write elsewhere. My question is, where is the implementation of "localStorage" used in AuthContext.js? As far as I can see, you upload it in the backend without a database. Is it feasible to upload from a database?

**Comment by ivangfr** [comment]
Hi @Davessonn thanks for the command.

_"localStorage is one of the two mechanisms of a browser’s web storage. It allows users to save data as key-value pairs in the browser for later use."_ More info [here](https://blog.logrocket.com/using-localstorage-react-hooks/)

It's used in the `AuthProvider` to save the user's info when he/she logs in and, it's removed when the user logs out.

Then, we can use the following methods: `getUser`, `userIsAuthenticated`, `userLogin`, and `userLogout`.

I hope I was able to answer your question.
